# Site settings
title: 西电睿思 | rs.xidian.edu.cn
copyleft: 2009-2023 ❤ 西电睿思
description: 西电睿思,睿思,瑞斯,瑞思,睿思bt,睿思bbs,西电睿思网址,睿思邀请码,睿思pt
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rs.xidian.edu.cn" # the base hostname & protocol for your site
